# Generated by Django 3.1.8 on 2021-04-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Case_Number', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('Person_name', models.CharField(max_length=30)),
                ('Identity_Document_Number', models.CharField(max_length=10)),
                ('Date_of_Birth', models.CharField(max_length=30)),
                ('Date_of_Symptons', models.CharField(max_length=30)),
                ('Date_of_Confirmation', models.CharField(max_length=30)),
            ],
        ),
    ]
