# Generated by Django 3.1.8 on 2021-05-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0003_auto_20210425_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Date_of_Birth',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='Date_of_Confirmation',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='Date_of_Symptons',
            field=models.DateField(max_length=30),
        ),
    ]
