# Generated by Django 3.1.8 on 2021-05-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('xCoord', models.FloatField(null=True)),
                ('yCoord', models.FloatField(null=True)),
                ('date', models.DateField()),
                ('number_of_cases', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Case.case')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.publicevent')),
            ],
        ),
    ]
