# Generated by Django 3.1.8 on 2021-05-01 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('Case_Number', models.CharField(max_length=30, unique=True)),
                ('Person_name', models.CharField(max_length=30)),
                ('Identity_Document_Number', models.CharField(max_length=10)),
                ('Date_of_Birth', models.DateField()),
                ('Date_of_Symptoms', models.DateField()),
                ('Date_of_Confirmation', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['Case_Number'],
            },
        ),
    ]
