# Generated by Django 3.1.8 on 2021-04-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0002_auto_20210425_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Case_Number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
