# Generated by Django 3.1.8 on 2021-05-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0005_auto_20210501_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='Date_of_Symptons',
            new_name='Date_of_Symptoms',
        ),
    ]
