# Generated by Django 3.1.8 on 2021-05-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0006_auto_20210501_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Case_Number',
            field=models.CharField(max_length=30),
        ),
    ]
