# Generated by Django 3.1.8 on 2021-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0007_auto_20210505_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Case_Number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Identity_Document_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
