# Generated by Django 3.1.8 on 2021-05-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicevent',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publicevent',
            name='number_of_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicevent',
            name='xCoord',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='publicevent',
            name='yCoord',
            field=models.FloatField(null=True),
        ),
    ]
